version: doc"3"

services:
  fe-covidstat:
    build: .
    # specifying the image-name for the image built using dockerfile
    image: "covistat-fe:0.0.1"
    tag: 
    container_name: "covidstat-service-fe"
    networks:
      - casestudy
    ports:
      - "3000:80
    environment:
      - API_KEY=${API_KEY}

networks:
  casestudy:
    external: true